[package]
name = "tmux-as-code"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["cargo"] }
serde = { version = "1.0.218", features = ["serde_derive"] }
tmux_interface = "0.3.2"
toml = "0.8.20"
tracing = "0.1"
tracing-subscriber = "0.3"
